Repository scireum/sirius-kernel, pull requests merged in 2020-06, with the labels that each got.

#270 Make the docker.file config a list
  src/main/java/sirius/kernel/DockerHelper.java
Labels:  💣 BREAKING CHANGE, 🧬 Enhancement

#271 Marks Transformer as AutoRegister
  .gitignore
  src/main/java/sirius/kernel/di/transformers/Transformer.java
Labels: 👶🏻 Trivial

#272 Adds support for paths like /foo/bar in XMLReader.
  src/main/java/sirius/kernel/xml/XMLReader.java
  src/test/java/sirius/kernel/xml/XMLReaderSpec.groovy
Labels: 🧬 Enhancement

#273 Prevents overuse of Redis via coherent caches
  src/main/java/sirius/kernel/cache/CacheCoherence.java
  src/main/java/sirius/kernel/cache/CacheManager.java
  src/main/java/sirius/kernel/cache/CoherentCache.java
Labels:  💣 BREAKING CHANGE, 🐛 Bugfix
