Repository scireum/sirius-kernel, pull requests merged in 2020-11, with the labels that each got.

#296 Corrects czech date pattern
  src/main/resources/kernel_cs.properties
Labels: 🐛 Bugfix, 👶🏻 Trivial

#297 Fixes erroneous report of background loop overtime
  src/main/java/sirius/kernel/async/BackgroundLoop.java
  src/main/java/sirius/kernel/health/metrics/SystemMetricProvider.java
Labels: 🐛 Bugfix

#300 Sort caches in the cache-command
  src/main/java/sirius/kernel/cache/CacheManager.java
Labels: 👶🏻 Trivial, 🧬 Enhancement
