Repository scireum/sirius-kernel, pull requests merged in 2020-03, with the labels that each got.

#244 "Fixes" the cache coherence of Cache.removeIf
  src/main/java/sirius/kernel/cache/Cache.java
  src/main/java/sirius/kernel/cache/CacheCoherence.java
  src/main/java/sirius/kernel/cache/CacheManager.java
  src/main/java/sirius/kernel/cache/CoherentCache.java
  src/main/java/sirius/kernel/cache/ManagedCache.java
  src/test/java/sirius/kernel/cache/ManagedCacheSpec.groovy
Labels:  💣 BREAKING CHANGE, 🐛 Bugfix

#245 New Framework: End of Day Tasks
  src/main/java/sirius/kernel/health/Exceptions.java
  src/main/java/sirius/kernel/health/MemoryBasedHealthMonitor.java
  src/main/java/sirius/kernel/health/console/EndOfDayCommand.java
  src/main/java/sirius/kernel/timer/EndOfDayTask.java
  src/main/java/sirius/kernel/timer/EndOfDayTaskExecutor.java
  src/main/java/sirius/kernel/timer/EndOfDayTaskInfo.java
  src/main/java/sirius/kernel/timer/EveryDay.java
  src/main/java/sirius/kernel/timer/Timers.java
  src/main/resources/component-kernel.conf
  src/test/java/sirius/kernel/timer/EndOfDayTestTask.java
  src/test/java/sirius/kernel/timer/EveryDayTaskSpec.groovy
Labels: 🧬 Enhancement

#246 Fixes a potential NPE during system startup.
  src/main/java/sirius/kernel/cache/ManagedCache.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#247 Creates new method to mark the outcall as post request
  src/main/java/sirius/kernel/xml/Outcall.java
Labels: 👶🏻 Trivial, 🧬 Enhancement
