Repository scireum/sirius-kernel, pull requests merged in 2020-02, with the labels that each got.

#239 Adds an appropriate annotation.
  src/main/java/sirius/kernel/xml/StructuredNode.java
Labels: 👶🏻 Trivial, 🧬 Enhancement

#237 BREAKING: Specifies functional interface as indicated by sonarqube
  src/main/java/sirius/kernel/commons/Strings.java
Labels:  💣 BREAKING CHANGE, 🎁 Next version, 👶🏻 Trivial

#241 More robust lazy language installers.
  src/main/java/sirius/kernel/async/CallContext.java
  src/main/java/sirius/kernel/di/transformers/Transformers.java
Labels: 🐛 Bugfix
