Repository scireum/sirius-kernel, pull requests merged in 2021-04, with the labels that each got.

#326 Renames the multiplyPercent method as its name is highly misleading.
  src/main/java/sirius/kernel/commons/Amount.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#327 Allows getting a config list from a settings object
  src/main/java/sirius/kernel/settings/Settings.java
Labels: 🧬 Enhancement

#328 Output namespaced xml property only if value is not null
  src/main/java/sirius/kernel/xml/XMLStructuredOutput.java
Labels: 👶🏻 Trivial, 🧬 Enhancement

#329 BREAKING CHANGE: Fixes rounding of Amount.
  pom.xml
  src/main/java/sirius/kernel/commons/Amount.java
  src/main/java/sirius/kernel/nls/NLS.java
  src/main/java/sirius/kernel/xml/XMLStructuredOutput.java
  src/main/resources/component-kernel.conf
  src/test/java/sirius/kernel/commons/AmountSpec.groovy
Labels:  💣 BREAKING CHANGE, 🐛 Bugfix

#330 Preserves whitespaces when outputting XML.
  src/main/java/sirius/kernel/xml/AbstractStructuredOutput.java
  src/main/java/sirius/kernel/xml/XMLStructuredOutput.java
Labels: 🐛 Bugfix, 👶🏻 Trivial
