Repository scireum/sirius-kernel, pull requests merged in 2021-03, with the labels that each got.

#317 Stops auto transforming GET requests into POST Requests and adds some methods to Outcall
  src/main/java/sirius/kernel/xml/Outcall.java
Labels:  💣 BREAKING CHANGE, 🧬 Enhancement

#318 Marks XMLCalls as POST requests if a XMLStructuredOutput is created
  src/main/java/sirius/kernel/xml/XMLCall.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#319 Stops NPE when trying to parse a non-existent content-disposition header
  src/main/java/sirius/kernel/xml/Outcall.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#320 No longer disables doInput for 'HEAD' requests
  src/main/java/sirius/kernel/xml/Outcall.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#323 SoapClient: fix debugging output
  src/main/java/sirius/kernel/xml/SOAPClient.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#321 Only marks a field as accessible if we plan to update it.
  src/main/java/sirius/kernel/di/PartRegistry.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#324 Cleanup of TaskContext and async APIs.
  src/main/java/sirius/kernel/async/Barrier.java
  src/main/java/sirius/kernel/async/BasicTaskContextAdapter.java
  src/main/java/sirius/kernel/async/CombinedFuture.java
  src/main/java/sirius/kernel/async/TaskContext.java
  src/main/java/sirius/kernel/async/TaskContextAdapter.java
  src/main/java/sirius/kernel/commons/Callback.java
  src/main/java/sirius/kernel/commons/Processor.java
  src/main/java/sirius/kernel/commons/Producer.java
  src/main/java/sirius/kernel/commons/RateLimit.java
  src/test/java/sirius/kernel/async/CombinedFutureTest.java
Labels: 🐛 Bugfix
