Repository scireum/sirius-kernel, pull requests merged in 2021-10, with the labels that each got.

#360 Strings: URL Decoding
  src/main/java/sirius/kernel/commons/Strings.java
  src/test/java/sirius/kernel/commons/StringsTest.java
Labels: 👶🏻 Trivial

#359 Add a Strings.splitSmart to split a large string into partial strings
  src/main/java/sirius/kernel/commons/Strings.java
  src/test/java/sirius/kernel/commons/StringsTest.java
Labels: 🧬 Enhancement

#362 BREAKING: Removes deprecated methods from NLS
  src/main/java/sirius/kernel/nls/NLS.java
  src/main/resources/component-kernel.conf
Labels:  💣 BREAKING CHANGE
