Repository scireum/sirius-kernel, pull requests merged in 2021-06, with the labels that each got.

#332 Makes Frequency constants available for implementing classes
  src/main/java/sirius/kernel/async/BackgroundLoop.java
Labels: 👶🏻 Trivial

#334 Always resolves the com.typesafe.config.Config object before it is accessed via Sirius' Settings
  src/main/java/sirius/kernel/settings/Settings.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#336 activate nightly tests in drone
  .drone.yml
  README.md
  src/test/java/sirius/kernel/ScenarioSuite.java
  src/test/java/sirius/kernel/Scope.java
Labels: 👶🏻 Trivial

#338 Deprecates methods related to language validation in NLS.
  src/main/java/sirius/kernel/nls/NLS.java
Labels:  💣 BREAKING CHANGE, 👶🏻 Trivial
