Repository scireum/sirius-kernel, pull requests merged in 2021-08, with the labels that each got.

#347 Disables jar connection caching to be able to hotswap libs
  src/main/java/sirius/kernel/Sirius.java
Labels: 🧬 Enhancement

#348 Simplifies method call with overloaded method
  src/main/java/sirius/kernel/nls/NLS.java
Labels: 👶🏻 Trivial

#349 Adds record support for StructuredOutput.
  src/main/java/sirius/kernel/xml/AbstractStructuredOutput.java
  src/main/java/sirius/kernel/xml/StructuredOutput.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#350 Adds support for protocol changing HTTP redirects.
  src/main/java/sirius/kernel/xml/Outcall.java
Labels: 🧬 Enhancement

#351 Provides Value.tryAppend which only appends to a non-empty Value + Improvement for Outcall
  src/main/java/sirius/kernel/commons/Amount.java
  src/main/java/sirius/kernel/commons/Value.java
  src/main/java/sirius/kernel/xml/Outcall.java
  src/test/java/sirius/kernel/commons/ValueSpec.groovy
Labels: 🧬 Enhancement

#352 Allows to alter the default level of all loggers
  src/main/java/sirius/kernel/Setup.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#353 Permits to add hints into existing handled exceptions
  src/main/java/sirius/kernel/health/HandledException.java
Labels: 🧬 Enhancement
