Repository scireum/sirius-kernel, pull requests merged in 2022-02, with the labels that each got.

#381 Logs the current execution point alongside missing translations
  src/main/java/sirius/kernel/nls/Babelfish.java
Labels: 👶🏻 Trivial

#382 Trie: Consistently returns an unmodifiable key set
  src/main/java/sirius/kernel/commons/Trie.java
Labels: 🐛 Bugfix,  💣 BREAKING CHANGE

#383 Adds own redirect logic to support unencoded location headers
  src/main/java/sirius/kernel/xml/Outcall.java
Labels: 🧬 Enhancement
