Repository scireum/sirius-kernel, pull requests merged in 2022-10, with the labels that each got.

#407 Updates some dependencies (slf4j is breaking!)
  pom.xml
  src/test/java/sirius/kernel/nls/NLSSpec.groovy
Labels:  💣 BREAKING CHANGE, 👶🏻 Trivial, dependencies

#408 Uses the correct date time format for the If-Modified-Since header
  src/main/java/sirius/kernel/xml/Outcall.java
Labels: 🐛 Bugfix

#409 Backports HTTP date format
  src/main/java/sirius/kernel/xml/Outcall.java
Labels: 🐛 Bugfix

#411 Gradle: Sets up SonarQube
  .drone.yml
  build.gradle.kts
Labels: 🎁 Next version

#412 Adds new methods for safely adding path parts to an URL builder
  src/main/java/sirius/kernel/commons/URLBuilder.java
  src/test/java/sirius/kernel/commons/URLBuilderSpec.groovy
Labels: 🧬 Enhancement

#413 SIRI-655 make Strings#splitSmart nullsafe
  src/main/java/sirius/kernel/commons/CachingSupplier.java
  src/main/java/sirius/kernel/commons/CommandParser.java
  src/main/java/sirius/kernel/commons/Context.java
  src/main/java/sirius/kernel/commons/Explain.java
  src/main/java/sirius/kernel/commons/Limit.java
  src/main/java/sirius/kernel/commons/NumberFormat.java
  src/main/java/sirius/kernel/commons/Strings.java
  src/main/java/sirius/kernel/commons/Tuple.java
  src/main/java/sirius/kernel/commons/Wait.java
  src/test/java/sirius/kernel/commons/StringsTest.java
Labels: 👶🏻 Trivial
