Repository scireum/sirius-kernel, pull requests merged in 2023-05, with the labels that each got.

#450 Defines a JS formatter
  src/main/java/sirius/kernel/nls/Formatter.java
  src/test/java/sirius/kernel/nls/FormatterSpec.groovy
Labels: 🧬 Enhancement

#451 Prepares switching JSON handling from FastJSON to Jackson
  build.gradle.kts
  pom.xml
  src/main/java/sirius/kernel/AutoSetup.java
  src/main/java/sirius/kernel/Classpath.java
  src/main/java/sirius/kernel/DockerHelper.java
  src/main/java/sirius/kernel/Setup.java
  src/main/java/sirius/kernel/Sirius.java
  src/main/java/sirius/kernel/async/BackgroundLoop.java
  src/main/java/sirius/kernel/async/CallContext.java
  src/main/java/sirius/kernel/async/Promise.java
  src/main/java/sirius/kernel/async/Tasks.java
  src/main/java/sirius/kernel/cache/ManagedCache.java
  src/main/java/sirius/kernel/commons/Exec.java
  src/main/java/sirius/kernel/commons/Files.java
  src/main/java/sirius/kernel/commons/Hasher.java
  src/main/java/sirius/kernel/commons/Json.java
  src/main/java/sirius/kernel/commons/Reflection.java
  src/main/java/sirius/kernel/commons/Strings.java
  src/main/java/sirius/kernel/commons/URLBuilder.java
  src/main/java/sirius/kernel/commons/Value.java
  src/main/java/sirius/kernel/commons/Wait.java
  src/main/java/sirius/kernel/di/Injector.java
  src/main/java/sirius/kernel/di/PartRegistry.java
  src/main/java/sirius/kernel/di/transformers/AutoTransformLoadAction.java
  src/main/java/sirius/kernel/health/Exceptions.java
  src/main/java/sirius/kernel/health/Log.java
  src/main/java/sirius/kernel/health/metrics/Metrics.java
  src/main/java/sirius/kernel/nls/NLS.java
  src/main/java/sirius/kernel/settings/Extension.java
  src/main/java/sirius/kernel/settings/PortMapper.java
  src/main/java/sirius/kernel/settings/Settings.java
  src/main/java/sirius/kernel/timer/EndOfDayTaskExecutor.java
  src/main/java/sirius/kernel/timer/Timers.java
  src/main/java/sirius/kernel/tokenizer/LookaheadReader.java
  src/main/java/sirius/kernel/xml/AbstractStructuredOutput.java
  src/main/java/sirius/kernel/xml/ContentDispositionParser.java
  src/main/java/sirius/kernel/xml/Outcall.java
  src/main/java/sirius/kernel/xml/StructuredNode.java
  src/main/java/sirius/kernel/xml/XMLCall.java
  src/main/java/sirius/kernel/xml/XMLGenerator.java
  src/main/java/sirius/kernel/xml/XMLReader.java
  src/main/java/sirius/kernel/xml/XMLStructuredInput.java
  src/test/java/sirius/kernel/ScenarioSuite.java
Labels: 🧬 Enhancement, ⬆️ Dependencies

#452 Expands and tests JSON Util Class
  src/main/java/sirius/kernel/commons/Json.java
  src/test/kotlin/sirius/kernel/commons/JsonTest.kt
Labels: 🧬 Enhancement

#453 Some more jackson / JSON helper methods
  src/main/java/sirius/kernel/commons/Json.java
  src/test/kotlin/sirius/kernel/commons/JsonTest.kt
Labels: 🧬 Enhancement

#455 Add support for CDATA in xml structured output
  src/main/java/sirius/kernel/xml/XMLStructuredOutput.java
Labels: 🧬 Enhancement

#457 Properly serializes and deserializes dates and times in JSON
  pom.xml
  src/main/java/sirius/kernel/commons/Json.java
  src/test/kotlin/sirius/kernel/commons/JsonTest.kt
Labels: 🐛 Bugfix
