Repository scireum/sirius-kernel, pull requests merged in 2023-06, with the labels that each got.

#460 Uses toMachineString for Amount serialization
  src/main/java/sirius/kernel/commons/Amount.java
Labels: 🧬 Enhancement

#461 Makes Amount serialized as number in json
  src/main/java/sirius/kernel/commons/Amount.java
Labels: 🐛 Bugfix

#463 Enables json number to Amount mapping
  src/main/java/sirius/kernel/commons/Amount.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#464 Provides a central method to cleanup / normalize strings
  src/main/java/sirius/kernel/commons/Cleanup.java
  src/main/java/sirius/kernel/commons/Strings.java
  src/test/java/sirius/kernel/commons/StringsTest.java
Labels: 🧬 Enhancement

#467 Fixes Promise#asFuture method
  src/main/java/sirius/kernel/async/Promise.java
  src/test/java/sirius/kernel/async/PromiseSpec.groovy
  src/test/kotlin/sirius/kernel/async/PromiseTest.kt
Labels: 🐛 Bugfix
