Repository scireum/sirius-kernel, pull requests merged in 2023-07, with the labels that each got.

#468 Makes StringCleanups more versatile.
  src/main/java/sirius/kernel/commons/Cleanup.java
  src/main/java/sirius/kernel/commons/Files.java
  src/main/java/sirius/kernel/commons/StringCleanup.java
  src/main/java/sirius/kernel/commons/Strings.java
  src/test/java/sirius/kernel/commons/StringsTest.java
Labels: 💣 BREAKING CHANGE, 🧬 Enhancement

#470 Tiny docs & GC fix for Strings.cleanup
  src/main/java/sirius/kernel/commons/StringCleanup.java
  src/main/java/sirius/kernel/commons/Strings.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#471 Permits specifying a formatter in NLS.get(count)
  src/main/java/sirius/kernel/nls/NLS.java
  src/test/java/sirius/kernel/nls/NLSSpec.groovy
Labels: 🧬 Enhancement, 👶🏻 Trivial

#475 Fixes the wrong file extension extraction for paths like test.a/12345
  src/main/java/sirius/kernel/commons/Files.java
  src/test/java/sirius/kernel/commons/FilesTest.java
  src/test/kotlin/sirius/kernel/commons/FilesTest.kt
Labels: 🐛 Bugfix

#476 Adjusts regex to only match valid html tags starting with letters
  src/main/java/sirius/kernel/commons/Strings.java
  src/test/java/sirius/kernel/commons/StringsTest.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#472 Improves XML detection and adds HTML string cleanup methods
  src/main/java/sirius/kernel/commons/StringCleanup.java
  src/main/java/sirius/kernel/commons/Strings.java
  src/test/java/sirius/kernel/commons/StringsTest.java
Labels: 🧬 Enhancement

#478 Migrates some tests to jUnit5
  src/test/java/sirius/kernel/async/CombinedFutureTest.java
  src/test/java/sirius/kernel/commons/BOMReaderTest.java
  src/test/java/sirius/kernel/commons/HasherTest.java
  src/test/java/sirius/kernel/commons/MultiMapTest.java
  src/test/java/sirius/kernel/commons/PriorityCollectorTest.java
  src/test/java/sirius/kernel/commons/StreamsTest.java
  src/test/java/sirius/kernel/commons/StringsTest.java
  src/test/java/sirius/kernel/commons/TrieTest.java
  src/test/java/sirius/kernel/commons/ValuesTest.java
  src/test/java/sirius/kernel/health/ExceptionsTest.java
  src/test/java/sirius/kernel/health/LogHelper.java
  src/test/java/sirius/kernel/nls/FormatterSpec.groovy
  src/test/java/sirius/kernel/settings/ConfigBuilderSpec.groovy
  src/test/java/sirius/kernel/settings/SettingsSpec.groovy
  src/test/java/sirius/kernel/settings/SettingsTest.kt
  src/test/java/sirius/kernel/xml/ContentDispositionParserSpec.groovy
  src/test/java/sirius/kernel/xml/XMLReaderTest.java
  src/test/kotlin/sirius/kernel/async/CombinedFutureTest.kt
  src/test/kotlin/sirius/kernel/async/PromiseTest.kt
  src/test/kotlin/sirius/kernel/commons/BOMReaderTest.kt
  src/test/kotlin/sirius/kernel/commons/FilesTest.kt
  src/test/kotlin/sirius/kernel/commons/HasherTest.kt
  src/test/kotlin/sirius/kernel/commons/JsonTest.kt
  src/test/kotlin/sirius/kernel/commons/MultiMapTest.kt
  src/test/kotlin/sirius/kernel/commons/PriorityCollectorTest.kt
  src/test/kotlin/sirius/kernel/commons/StreamsTest.kt
  src/test/kotlin/sirius/kernel/commons/StringsTest.kt
  src/test/kotlin/sirius/kernel/commons/TrieTest.kt
  src/test/kotlin/sirius/kernel/commons/ValuesTest.kt
  src/test/kotlin/sirius/kernel/health/ExceptionsTest.kt
  src/test/kotlin/sirius/kernel/health/LogHelper.kt
  src/test/kotlin/sirius/kernel/nls/FormatterTest.kt
  src/test/kotlin/sirius/kernel/settings/ConfigBuilderTest.kt
  src/test/kotlin/sirius/kernel/settings/SettingsTest.kt
  src/test/kotlin/sirius/kernel/testutil/Reflections.kt
  src/test/kotlin/sirius/kernel/xml/ContentDispositionParserTest.kt
  src/test/kotlin/sirius/kernel/xml/XmlReaderTest.kt
Labels: 🛠️ Maintenance
