Repository scireum/sirius-kernel, pull requests merged in 2023-02, with the labels that each got.

#425 Adds a method to MultiMap to get a unmodifiable keyset
  src/main/java/sirius/kernel/commons/MultiMap.java
Labels: 🧬 Enhancement

#431 Adds a common NLS key for "more"
  src/main/resources/kernel_de.properties
  src/main/resources/kernel_en.properties
Labels: 👶🏻 Trivial

#439 Gradle: resolves plugins from local first, then scireum repo, then gradle portal
  build.gradle.kts
  settings.gradle
  settings.gradle.kts
Labels: 👶🏻 Trivial

#433 Adds javadoc to method to document 'magic' behavior
  src/main/java/sirius/kernel/health/Exceptions.java
Labels: 👶🏻 Trivial, 🖐 Keep open

#441 Enhances parsing of strings into integer/longs
  src/main/java/sirius/kernel/commons/Doubles.java
  src/main/java/sirius/kernel/nls/NLS.java
  src/test/java/sirius/kernel/nls/NLSSpec.groovy
Labels: 🧬 Enhancement

#443 BREAKING - NLS: Adds a method which converts a given time range in milliseconds to a time representation format typically found in digital clocks
  src/main/java/sirius/kernel/async/Operation.java
  src/main/java/sirius/kernel/commons/Watch.java
  src/main/java/sirius/kernel/nls/NLS.java
  src/main/java/sirius/kernel/timer/EndOfDayTaskInfo.java
  src/test/java/sirius/kernel/nls/NLSSpec.groovy
Labels: 💣 BREAKING CHANGE
