Repository scireum/sirius-kernel, pull requests merged in 2023-03, with the labels that each got.

#444 Fixes wrong duration being displayed in the watch
  src/main/java/sirius/kernel/commons/Watch.java
Labels: 👶🏻 Trivial

#445 update snakeyaml version like done in sirius-biz via dependabot
  pom.xml
Labels: 👶🏻 Trivial, ⬆️ Dependencies

#448 StructuredOutput: Properly handles ClosedChannelExceptions
  src/main/java/sirius/kernel/xml/AbstractStructuredOutput.java
  src/main/java/sirius/kernel/xml/XMLStructuredOutput.java
Labels: 🐛 Bugfix
