Repository scireum/sirius-kernel, pull requests merged in 2023-09, with the labels that each got.

#481 Brings oauth client support to Outcall
  src/main/java/sirius/kernel/xml/Outcall.java
Labels: 🧬 Enhancement

#488 JSON: Allows correctly fetching array node from constructed json tree
  src/main/java/sirius/kernel/commons/Json.java
  src/test/kotlin/sirius/kernel/commons/JsonTest.kt
Labels: 🐛 Bugfix, 👶🏻 Trivial

#490 jUnit: Migrates PullBasedSpliteratorTest to Kotlin
  src/test/java/sirius/kernel/commons/PullBasedSpliteratorTest.java
  src/test/kotlin/sirius/kernel/commons/PullBasedSpliteratorTest.kt
Labels: 🛠️ Maintenance

#492 `timer` Command with Force Mode (SIRI-872)
  src/main/java/sirius/kernel/health/console/TimerCommand.java
  src/main/java/sirius/kernel/timer/Timers.java
Labels: 🧬 Enhancement

#491 jUnit: Migrates BackgroundLoop Tests to Kotlin
  src/test/java/sirius/kernel/async/BackgroundLoopSpec.groovy
  src/test/kotlin/sirius/kernel/async/BackgroundLoopTest.kt
Labels: 🛠️ Maintenance

#493 Fixes a typo in the javadoc for Files#getFileExtension
  src/main/java/sirius/kernel/commons/Files.java
Labels: 👶🏻 Trivial

#494 Increases the maximum of parsed JSON strings
  pom.xml
  src/main/java/sirius/kernel/commons/Json.java
Labels: 🐛 Bugfix, 👶🏻 Trivial
