Repository scireum/sirius-kernel, pull requests merged in 2023-10, with the labels that each got.

#496 Adds a new helper for dates (called Dates) which provides convenience methods
  src/main/java/sirius/kernel/commons/Dates.java
  src/test/kotlin/sirius/kernel/commons/DatesTest.kt
Labels: 🧬 Enhancement

#497 Migrates last Specs from Groovy to Kotlin
  src/test/java/sirius/kernel/async/TasksSpec.groovy
  src/test/java/sirius/kernel/di/transformers/AutotransformerSpec.groovy
  src/test/java/sirius/kernel/di/transformers/TransformersSpec.groovy
  src/test/kotlin/sirius/kernel/async/BackgroundLoopTest.kt
  src/test/kotlin/sirius/kernel/async/TasksTest.kt
  src/test/kotlin/sirius/kernel/di/transformers/AutotransformerTest.kt
  src/test/kotlin/sirius/kernel/di/transformers/TransformerTest.kt
Labels: 👶🏻 Trivial, 🛠️ Maintenance

#499 Ensures a proper load order for component-x.conf files
  README.md
  src/main/java/sirius/kernel/Setup.java
  src/main/java/sirius/kernel/Sirius.java
  src/main/java/sirius/kernel/async/Operation.java
  src/main/java/sirius/kernel/cache/README.md
  src/main/java/sirius/kernel/info/README.md
  src/main/java/sirius/kernel/timer/EndOfDayTaskExecutor.java
  src/main/java/sirius/kernel/timer/Timers.java
  src/main/java/sirius/kernel/xml/Outcall.java
  src/main/resources/component-050-kernel.conf
Labels: 🧬 Enhancement

#500 Sorts component conf files in the correct order
  src/main/java/sirius/kernel/Sirius.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#501 Adds a supplier to enable or disable the soap and xml-call fine-logging
  src/main/java/sirius/kernel/xml/SOAPClient.java
  src/main/java/sirius/kernel/xml/XMLCall.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#502 Detects entities in texts to decide if its xml
  src/main/java/sirius/kernel/commons/StringCleanup.java
  src/main/java/sirius/kernel/commons/Strings.java
  src/test/kotlin/sirius/kernel/commons/StringsTest.kt
Labels: 🧬 Enhancement

#503 Switch project to Java 21
  .drone.yml
  pom.xml
  src/main/java/sirius/kernel/async/CallContext.java
  src/main/java/sirius/kernel/commons/Exec.java
  src/main/java/sirius/kernel/commons/URLBuilder.java
  src/main/java/sirius/kernel/health/console/ThreadsCommand.java
  src/main/java/sirius/kernel/xml/Outcall.java
  src/main/java/sirius/kernel/xml/XMLReader.java
  src/test/kotlin/sirius/kernel/async/TasksTest.kt
  src/test/kotlin/sirius/kernel/cache/ManagedCacheTest.kt
  src/test/kotlin/sirius/kernel/commons/ValueTest.kt
  src/test/kotlin/sirius/kernel/xml/XmlReaderTest.kt
Labels: 💣 BREAKING CHANGE, 🛠️ Maintenance

#504 Emojis 15.1
  src/main/java/sirius/kernel/commons/Emojis.java
Labels: 👶🏻 Trivial

#505 Configurable Outcall blacklisting
  src/main/java/sirius/kernel/xml/Outcall.java
  src/main/java/sirius/kernel/xml/XMLCall.java
Labels: 🧬 Enhancement
