Repository scireum/sirius-kernel, pull requests merged in 2023-12, with the labels that each got.

#508 Fixes Amount in Json problems with regards to precision
  src/main/java/sirius/kernel/commons/Amount.java
  src/main/java/sirius/kernel/commons/Json.java
  src/test/kotlin/sirius/kernel/commons/JsonTest.kt
Labels: 🐛 Bugfix, 🎁 Next version

#510 Simplifies code by utilizing sequenced collection helpers
  src/main/java/sirius/kernel/Classpath.java
  src/main/java/sirius/kernel/async/Promises.java
  src/main/java/sirius/kernel/async/Tasks.java
  src/main/java/sirius/kernel/cache/ManagedCache.java
  src/main/java/sirius/kernel/health/MemoryBasedHealthMonitor.java
  src/main/java/sirius/kernel/health/console/TimerCommand.java
  src/main/java/sirius/kernel/nls/Formatter.java
  src/main/java/sirius/kernel/tokenizer/Lookahead.java
  src/main/java/sirius/kernel/tokenizer/ParseException.java
  src/main/java/sirius/kernel/xml/AbstractStructuredOutput.java
  src/main/java/sirius/kernel/xml/XMLReader.java
Labels: 🎁 Next version, 🛠️ Maintenance

#512 Update some dependencies
  .run/mvn clean test - without nightly.run.xml
  pom.xml
  src/test/java/sirius/kernel/NightlyTest.java
Labels: ⬆️ Dependencies

#513 upgrade to latest parent-version
  pom.xml
Labels: ⬆️ Dependencies
