Repository scireum/sirius-kernel, pull requests merged in 2024-12, with the labels that each got.

#540 add an often needed isHttpUrl check to Strings
  src/main/java/sirius/kernel/commons/Strings.java
  src/test/kotlin/sirius/kernel/commons/StringsTest.kt
Labels: 🧬 Enhancement, 👶🏻 Trivial

#542 Upgrade library versions
  .drone.yml
  pom.xml
Labels: ⬆️ Dependencies

#543 SIRI-1037 Fix potential XXE vulnerability
  src/main/java/sirius/kernel/xml/XMLGenerator.java
  src/main/java/sirius/kernel/xml/XMLReader.java
  src/main/java/sirius/kernel/xml/XMLStructuredInput.java
  src/test/kotlin/sirius/kernel/xml/XmlReaderTest.kt
Labels: 🐛 Bugfix
