Repository scireum/sirius-kernel, pull requests merged in 2024-04, with the labels that each got.

#519 Update some dependencies to their latest versions
  build.gradle.kts
  pom.xml
Labels: 👶🏻 Trivial, ⬆️ Dependencies, 🛠️ Maintenance

#521 Update sirius parent to version targeting Java 22
  .drone.yml
  pom.xml
Labels: 👶🏻 Trivial, ⬆️ Dependencies, 🛠️ Maintenance

#520 SE-13616: Adjusts key and translation for clarity.
  src/main/java/sirius/kernel/nls/NLS.java
  src/main/resources/kernel_cs.properties
  src/main/resources/kernel_de.properties
  src/main/resources/kernel_en.properties
  src/main/resources/kernel_fr.properties
  src/main/resources/kernel_it.properties
  src/main/resources/kernel_nl.properties
  src/main/resources/kernel_pl.properties
  src/test/kotlin/sirius/kernel/nls/NLStest.kt
Labels: 👶🏻 Trivial, 🛠️ Maintenance

#523 StringCleanup - Allow to capitalize strings
  src/main/java/sirius/kernel/commons/StringCleanup.java
  src/test/kotlin/sirius/kernel/commons/StringsTest.kt
Labels: 🧬 Enhancement, 👶🏻 Trivial
