Repository scireum/sirius-kernel, pull requests merged in 2024-11, with the labels that each got.

#537 remove leftover config-values and correct wording
  src/main/resources/component-050-kernel.conf
Labels: 👶🏻 Trivial, 🛠️ Maintenance

#538 Lokalise: Translations update
  src/main/resources/kernel_es.properties
  src/main/resources/kernel_sk.properties
Labels: 🧬 Enhancement

#541 Fixes a race condition in auto tranformer
  src/main/java/sirius/kernel/di/transformers/AutoTransformLoadAction.java
Labels: 🐛 Bugfix, 👶🏻 Trivial
