Repository scireum/sirius-kernel, pull requests merged in 2025-03, with the labels that each got.

#551 Adds a simple parallel task executor
  src/main/java/sirius/kernel/async/ParallelTaskExecutor.java
Labels: 🧬 Enhancement

#552 GA 12.0.0
  .drone.yml
  .github/PULL_REQUEST_TEMPLATE.md
  build.gradle.kts
  pom.xml
  src/main/java/sirius/kernel/commons/Dates.java
  src/main/java/sirius/kernel/commons/Files.java
  src/main/java/sirius/kernel/commons/StringCleanup.java
  src/main/java/sirius/kernel/commons/Strings.java
  src/main/java/sirius/kernel/commons/Value.java
  src/main/java/sirius/kernel/di/PartRegistry.java
  src/main/java/sirius/kernel/di/transformers/AutoTransformLoadAction.java
  src/main/java/sirius/kernel/health/Exceptions.java
  src/main/java/sirius/kernel/nls/NLS.java
  src/main/java/sirius/kernel/xml/XMLGenerator.java
  src/main/java/sirius/kernel/xml/XMLReader.java
  src/main/java/sirius/kernel/xml/XMLStructuredInput.java
  src/main/java/sirius/kernel/xml/XmlUtil.java
  src/main/resources/component-050-kernel.conf
  src/main/resources/kernel_cs.properties
  src/main/resources/kernel_de.properties
  src/main/resources/kernel_en.properties
  src/main/resources/kernel_es.properties
  src/main/resources/kernel_fr.properties
  src/main/resources/kernel_it.properties
  src/main/resources/kernel_nl.properties
  src/main/resources/kernel_pl.properties
  src/main/resources/kernel_sk.properties
  src/test/kotlin/sirius/kernel/commons/DatesTest.kt
  src/test/kotlin/sirius/kernel/commons/FilesTest.kt
  src/test/kotlin/sirius/kernel/commons/StringsTest.kt
  src/test/kotlin/sirius/kernel/commons/ValueTest.kt
  src/test/kotlin/sirius/kernel/nls/NLStest.kt
  src/test/kotlin/sirius/kernel/xml/XMLStructuredInputTest.kt
  src/test/kotlin/sirius/kernel/xml/XmlReaderTest.kt
Labels: 🛠️ Maintenance

#553 Upgrade maven parent for build plugins maintenance
  pom.xml
  src/test/java/TestSuite.java
  src/test/kotlin/sirius/kernel/commons/DatesTest.kt
  src/test/kotlin/sirius/kernel/settings/ConfigBuilderTest.kt
Labels: ⬆️ Dependencies

#555 Improves XML Query Performance when Handling Node List Items
  src/main/java/sirius/kernel/xml/StructuredNode.java
Labels: 🐛 Bugfix
