Repository scireum/sirius-kernel, pull requests merged in 2025-04, with the labels that each got.

#556 Reverts Breaking Change and introduces Alternative
  src/main/java/sirius/kernel/xml/StructuredNode.java
Labels: 🐛 Bugfix

#559 Emoji Update
  src/main/java/sirius/kernel/commons/Emojis.java
  src/test/kotlin/sirius/kernel/commons/EmojiTest.kt
Labels: 👶🏻 Trivial, 🛠️ Maintenance

#560 Lokalise: Translations update
  src/main/resources/kernel_cs.properties
  src/main/resources/kernel_en.properties
  src/main/resources/kernel_es.properties
  src/main/resources/kernel_fr.properties
  src/main/resources/kernel_it.properties
  src/main/resources/kernel_pl.properties
  src/main/resources/kernel_sk.properties
Labels: 🛠️ Maintenance

#561 Lokalise: Translations update
  src/main/resources/kernel_es.properties
Labels: 🐛 Bugfix, 🛠️ Maintenance

#562 Adds the Strings.areAllFilled
  src/main/java/sirius/kernel/commons/Strings.java
  src/test/kotlin/sirius/kernel/commons/StringsTest.kt
Labels: 💣 BREAKING CHANGE, 🧬 Enhancement, 🛠️ Maintenance
