Repository scireum/sirius-kernel, pull requests merged in 2025-06, with the labels that each got.

#569 Quoting in CSV writing allignment to rfc 4180
  src/main/java/sirius/kernel/commons/CSVWriter.java
  src/test/kotlin/sirius/kernel/commons/CSVReaderTest.kt
  src/test/kotlin/sirius/kernel/commons/CSVWriterTest.kt
Labels: 🧬 Enhancement

#570 Provide helper for quoting spaces in URLs
  src/main/java/sirius/kernel/commons/Strings.java
  src/main/java/sirius/kernel/commons/URLBuilder.java
  src/main/java/sirius/kernel/commons/Urls.java
  src/main/java/sirius/kernel/nls/Formatter.java
  src/test/kotlin/sirius/kernel/commons/StringsTest.kt
  src/test/kotlin/sirius/kernel/commons/UrlsTest.kt
Labels: 🧬 Enhancement, 👶🏻 Trivial

#571 Reverts broken blacklist log limitting
  src/main/java/sirius/kernel/xml/Outcall.java
Labels: 🐛 Bugfix
